### ISSUE TITLE
desiredCapabilities

### ISSUE THREAD

**Issue by mindlapse** [tipsi/tipsi-appium-helper#19]
Hi all!

I'm trying to fix the Travis android build for tipsi-stripe however the new emulator is slow and needs longer time limits.

When starting appium using the helper, I would like to set `desiredCapabilities` in `tipsi-appium-helper/src/core/configuration.js` as follows:

```
desiredCapabilities: { newCommandTimeout : "600000", androidInstallTimeout : 600000, automationName : "uiautomator2", uiautomator2ServerInstallTimeout : 600000 },
```
Currently, desiredCapabilities is set using an environment variable, however I need an object to be passed in like what is shown above.  Would it be possible to update the helper so that there is a way that parameters like these can be sent through the command line tool?

**Comment by mindlapse** [comment]
@cybergrind - I'm getting really close to having a working Travis build for tipsi-stripe on Android, but the above change is needed

**Comment by cybergrind** [comment]
Hey @mindlapse yep, we will add ability to pass config file instead of env variables.

**Comment by mindlapse** [comment]
That was fast, thanks so much! ⚡️
